//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Higi.Middleware.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SampleHigiMiddlewareDBEntities : DbContext
    {
        public SampleHigiMiddlewareDBEntities()
            : base("name=SampleHigiMiddlewareDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Higi_Client_Mappings> Higi_Client_Mappings { get; set; }
        public virtual DbSet<Target> Targets { get; set; }
        public virtual DbSet<ClientRequestResponse> ClientRequestResponses { get; set; }
        public virtual DbSet<HigiRequestResponse> HigiRequestResponses { get; set; }
        public virtual DbSet<QueueMessageStatu> QueueMessageStatus { get; set; }
    }
}
