//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Higi.Middleware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueueMessageStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QueueMessageStatu()
        {
            this.ClientRequestResponses = new HashSet<ClientRequestResponse>();
            this.HigiRequestResponses = new HashSet<HigiRequestResponse>();
        }
    
        public int MessageId { get; set; }
        public int HigiUserId { get; set; }
        public string Status { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientRequestResponse> ClientRequestResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HigiRequestResponse> HigiRequestResponses { get; set; }
    }
}
